### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'direnv'

### ISSUE THREAD

**Issue by Minabsapi** [74th/xonsh-direnv#11]
I installed this xontrib following the README, but upon starting another xonsh shell after installing I'm greeted with this:

```
Traceback (most recent call last):
  File "/home/minabsapi/.local/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 9562, in fire
    rv = handler(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/xontrib/direnv.xsh", line 36, in __direnv_postcommand
    __direnv()
  File "/usr/local/lib/python3.8/dist-packages/xontrib/direnv.xsh", line 7, in __direnv
    p = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'direnv'
Exception raised in event handler; ignored.
```

This is bad enough to trigger at every command as long as the xontrib is enabled.

Python version: Python 3.8.10
Xonsh version: 0.10.1
xonsh-direnv version: 1.5.0

**Comment by Shellcat-Zero** [comment]
I have this problem as well.

**Comment by 74th** [comment]
This plugin calls `direnv` program. Please install `direnv`.

```
# ubuntu
sudo apt install direnv

# macOS
brew install direnv
```

**Comment by Minabsapi** [comment]
Sorry, I assumed it was bundled. Although it might sound obvious, please mention it in the README
After installing it and enabling the xontrib again no error is occurring, so I guess the issue is fixed. Thank you
