### ISSUE TITLE
Unable to load xontrib direnv on Python 3.12

### ISSUE THREAD

**Issue by SamLukeYes** [74th/xonsh-direnv#16]
After updating Python to 3.12, this xontrib no longer loads.

```
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/parsers/fstring_adaptor.py", line 58, in _patch_special_syntax
    res = pyparse(repl)
          ^^^^^^^^^^^^^
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    f"{$DIRENV_DIR.strip('-')}"
       ^
SyntaxError: f-string: expecting a valid expression after '{'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/xontribs.py", line 246, in xontribs_load
    update_context(name, ctx=ctx, full_module=full_module)
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/xontribs.py", line 191, in update_context
    modctx = xontrib_context(name, full_module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/xontribs.py", line 157, in xontrib_context
    module = importlib.import_module(spec.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/z7xxy35k7620hs6fn6la5fg2lgklv72l-python3-3.12.4/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/imphooks.py", line 112, in get_code
    code = execer.compile(src, glbs=ctx, locs=ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/execer.py", line 131, in compile
    tree = self.parse(input, ctx, mode=mode, filename=filename, transform=transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/execer.py", line 87, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/execer.py", line 344, in _parse_ctx_free
    return _try_parse(input, greedy=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/execer.py", line 235, in _try_parse
    tree = self.parser.parse(
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/parsers/base.py", line 505, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/ply/ply/yacc.py", line 335, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/ply/ply/yacc.py", line 1122, in parseopt_notrack
    p.callable(pslice)
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/parsers/base.py", line 2522, in p_string_literal
    ).run()
      ^^^^^
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/parsers/fstring_adaptor.py", line 191, in run
    self._patch_special_syntax()
  File "/nix/store/qvsm2ny6g5hjfg49i1ca4rpr37md3i8b-python3-3.12.4-env/lib/python3.12/site-packages/xonsh/parsers/fstring_adaptor.py", line 74, in _patch_special_syntax
    raise RuntimeError("Unsupported fstring syntax") from e
RuntimeError: Unsupported fstring syntax
Failed to load xontrib direnv.
```

Seems related to https://github.com/xonsh/xonsh/issues/5166

**Comment by con-f-use** [comment]
Upstream issue.

**Comment by bestlem** [comment]
@con-f-use However upstream doesn't look like it will fix it soon so can't we change to a pure python code.
e.g.
```
direnv_dir = pf"{__xonsh__.env.get('DIRENV_DIR').strip('-')}"
```

**Comment by con-f-use** [comment]
We can, make a PR, I will review it.
