### ISSUE TITLE
Xontrib direnv fails to load through ~/.xonshrc in nested xonsh

### ISSUE THREAD

**Issue by SamLukeYes** [74th/xonsh-direnv#17]
When `xontrib load direnv` is in `~/.xonshrc`, `xonsh` command executed in xonsh shell immediately becomes a background job. When `$XONSH_DEBUG = 1` is set, the nested xonsh can launch, but with the following output:

```
<xonsh-code>:1:0 - xonsh
<xonsh-code>:1:0 + ![xonsh]
/home/yes/.xonshrc:11:8 - xontrib load coreutils
/home/yes/.xonshrc:11:8 + ![xontrib load coreutils]
/home/yes/.xonshrc:12:8 - xontrib load direnv
/home/yes/.xonshrc:12:8 + ![xontrib load direnv]
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/nix/store/4ykjgqb39nla095id5nk7hr7y28gc00s-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/xontribs.py", line 246, in xontribs_load
    update_context(name, ctx=ctx, full_module=full_module)
  File "/nix/store/4ykjgqb39nla095id5nk7hr7y28gc00s-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/xontribs.py", line 191, in update_context
    modctx = xontrib_context(name, full_module)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4ykjgqb39nla095id5nk7hr7y28gc00s-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/xontribs.py", line 157, in xontrib_context
    module = importlib.import_module(spec.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/hyppxdhgqx7nbg394j97yhmi6vizl074-python3-3.11.9/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/nix/store/4ykjgqb39nla095id5nk7hr7y28gc00s-python3-3.11.9-env/lib/python3.11/site-packages/xontrib/direnv.xsh", line 16, in <module>
    @events.on_post_rc
     
  File "/nix/store/4ykjgqb39nla095id5nk7hr7y28gc00s-python3-3.11.9-env/lib/python3.11/site-packages/xonsh/events.py", line 75, in __call__
    raise ValueError("Event handlers need a **kwargs for future proofing")
ValueError: Event handlers need a **kwargs for future proofing
Failed to load xontrib direnv.
```

Manually running `xontrib load direnv` without adding it to `~/.xonshrc` seems to be unaffected.

```
@ xonfig
+-----------------------------+--------------------+
| xonsh                       | 0.17.0             |
| Python                      | 3.11.9             |
| PLY                         | 3.11               |
| have readline               | True               |
| prompt toolkit              | 3.0.47             |
| shell type                  | prompt_toolkit     |
| history backend             | json               |
| pygments                    | 2.18.0             |
| on posix                    | True               |
| on linux                    | True               |
| distro                      | nixos              |
| on wsl                      | False              |
| on darwin                   | False              |
| on windows                  | False              |
| on cygwin                   | False              |
| on msys2                    | False              |
| is superuser                | False              |
| default encoding            | utf-8              |
| xonsh encoding              | utf-8              |
| encoding errors             | surrogateescape    |
| xontrib 1                   | coreutils          |
| xontrib 2                   | direnv             |
| xontrib 3                   | sh                 |
| RC file 1                   | /etc/xonsh/xonshrc |
| RC file 2                   | /home/yes/.xonshrc |
| UPDATE_OS_ENVIRON           | True               |
| XONSH_CAPTURE_ALWAYS        | False              |
| XONSH_SUBPROC_OUTPUT_FORMAT | stream_lines       |
| THREAD_SUBPROCS             | True               |
| XONSH_CACHE_SCRIPTS         | True               |
+-----------------------------+--------------------+
```

**Comment by SamLukeYes** [comment]
Just noticed that there's already an upstream issue https://github.com/xonsh/xonsh/issues/5244
~~and a PR to fix it https://github.com/74th/xonsh-direnv/pull/15~~ The PR doesn't fix this issue, but only suppresses the trace back :confused:

**Comment by SamLukeYes** [comment]
Probably duplicate of https://github.com/74th/xonsh-direnv/issues/14
